### ISSUE TITLE
Refactor tests to remove reliance on VLAs

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/ISO_Fortran_binding#10]
The core library builds with clang on macOS. However, one or more tests use VLAs. We should, at some point, refactor these to remove this.

**Comment by rouson** [comment]
Because the only _immediate_ prospects for use of this repository lie with GCC and because `gcc` supports non-standard VLAs as an extension, I'll mark this as "won't fix" and close it.  There's also at least one other Fortran compiler that uses `gcc` as its companion C compiler: the NAG Fortran compiler.   So there's also the possibility that this repository can be used with that compiler without removing VLAs.

The other open-source compiler that might have been a target for this repository's code is the [flang] compiler, but flang will at some point be replaced by [f18], which already has its own implementation of [ISO_Fortran_binding.h].

[flang]: https://github.com/flang-compiler/flang
[f18]: https://github.com/flang-compiler/f18
[ISO_Fortran_binding.h]: https://github.com/flang-compiler/f18/blob/master/include/flang/ISO_Fortran_binding.h

**Comment by zbeekman** [comment]
OK. It should be noted that most people consider this more than a cosmetic
problem, and consider VLAs to bee poor practice/dangerous, AFAICT, however
I doubt anyone will work on this anytime soon, so we may as well close it.
